### ISSUE TITLE
Hope to get the author's help

### ISSUE THREAD

**Issue by YHX-derc** [ishaanmht/PANet#1]
Dear Ishaan Mehta:
 I have recently read your article named "Pareto Frontier Approximation Network (PA-Net) to Solve Bi-objective TSP". I am very confused by a question in the article, and I hope to get your help and answer. I notice that when you transform the multi-objective optimization problem(TSP) in the paper into a constrained programming problem, the dot product constraint g is less than or equal to 0. But I found that g is actually a value greater than zero. I hope you can help me to answer my doubts. Thank you very much!!

**Comment by ishaanmht** [comment]
Hi 

Due to the nature of the optimization setup g can never be negative. Ideally, we would like g to be exactly zero i.e. the solution lies exactly on the preference. But due the combinatorial nature of the problem it is hard to find solutions that satisfy the constraint. However, with the lagrangian set up g can be used by the network to find solutions very close if not on the desired preference.
